%% Setting main frame

    bcolor = [1 1 1 ]/1.1;%/255;%[1 0 1];
    h.fig  = figure(1);clf

    set(h.fig, 'position',    [0 0 1300 750],...
               'color',       bcolor,...
               'menubar',     'none',...
               'toolbar',     'none',...
               'name',        'FAME',...
               'numbertitle', 'off');
    %% Setting main panels
    %panels position
    frame_postion = [    0  0.88     1  0.12 
                         0     0  0.65  0.88 
                      0.65     0  0.35  0.20 
                      0.65  0.20  0.35  0.68 ]; 
    nframe      = size(frame_postion,1);
    %set panel
    for i = 1:nframe
        h.frame(i) = uipanel( 'parent',          h.fig,...
                              'units',           'normalized',...
                              'backgroundcolor', bcolor,...
                              'ForegroundColor', [1 1 1],...
                              'shadowcolor',     [.9 .9 .98]/3,...
                              'bordertype',      'beveledin',...
                              'borderwidth',     4,...
                              'position',        frame_postion(i,:));
    end
    %% frame(1) contents
    % TEXT: Display Current Type 
    h.log_text(1) = uicontrol( 'parent',          h.frame(1),...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'Isotropic (Simple Cubic)',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 .1 1],...
                               'fontsize',        16,...
                               'position',        [.6 .55 .35 .35]);
    %TEXT: Display current chosen wave vector
    h.log_text(2) = uicontrol( 'parent',          h.frame(1),...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          [],...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [1 0 .1],...
                               'fontsize',        16,...
                               'position',        [.6 .01 .3 .3]);
    %AXES: Display FAME Logo
    h.ax_logo = axes( 'parent',   h.frame(1),...
                      'position', [-.3 -.9 .8 2.8],...
                      'xcolor',   [1 1 1],...
                      'ycolor',   [1 1 1]); 
    load fame
    patch('vertices',v,'faces',f(:,2:4)+1,'Facecolor',[0 0 1],'edgecolor','none','LineWidth',1,'FaceLighting','phong');
    for i=1:2
        light('Position',[-1 1 -1],'Style','infinite');
        light('Position',[1 0 0],'Style','infinite');
        light('Position',[0 -1 0],'Style','infinite');
    end
    lighting phong
    axis equal
    axis off
    view(0,15);
    %PUSH: clear all button
    h.push_clear = uicontrol( 'parent',          h.frame(1),...
                              'style',           'push',...
                              'units',           'normalized',...
                              'ForegroundColor', [0 0 0],...
                              'position',        [.9,.01,.08,.33],...
                              'string',          'Clear all',...
                              'fontsize',        14);
   %CHECK: Muti-core check box
%    h.check_muticore = uicontrol( 'parent',          h.frame(1),...
%                                  'style',           'check',...
%                                  'units',           'normalized',...
%                                  'string',          'Multi-Core',...
%                                  'backgroundcolor', bcolor,...
%                                  'ForegroundColor', [1 0 .1],...
%                                  'fontsize',        16,...
%                                  'position',        [.45 .01 .35 .3]);
    %% frame(2) contents
    % AXES: Display band structure
    h.ax_band = axes( 'parent',   h.frame(2),...
                      'position', [.1 .15 .8 .7],...
                      'xcolor',   [1 1 1],...
                      'visible',  'off',...
                      'ycolor',   [1 1 1]);
    % PUSH: choose wave vector
    h.hpush_eigenmode = uicontrol( 'parent',          h.frame(2),...
                                   'style',           'push',...
                                   'units',           'normalized',...
                                   'string',          'choose wave vector',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [.2 0 1],...
                                   'visible',         'off',...
                                   'fontsize',        16,...
                                   'position',        [.7 .01 .3 .05]);            
    % Subpanel for show 3D structure
    h.frame_show3D_unit = uipanel( 'parent',          h.frame(2),...
                              'units',           'normalized',...
                              ...'title',frame_title{i},...
                              'backgroundcolor', [.9 .9 .9],...
                              'ForegroundColor', [.5 1 1],...
                              'shadowcolor',     [.5 .9 .98],...
                              ...'bordertype','beveledin',...
                              'borderwidth',     0,...
                              'position',        [0,0,1,1],... [0.005,0.005,.64,.87]
                              'visible',         'off');
    h.frame_show3D_prim = uipanel( 'parent',          h.frame(2),...
                              'units',           'normalized',...
                              ...'title',frame_title{i},...
                              'backgroundcolor', [.9 .9 .9],...
                              'ForegroundColor', [.5 1 1],...
                              'shadowcolor',     [.5 .9 .98],...
                              ...'bordertype','beveledin',...
                              'borderwidth',     0,...
                              'position',        [0,0,1,1],... [0.005,0.005,.64,.87]
                              'visible',         'off');
    h.ax_show3D_unit = axes('parent',h.frame_show3D_unit);
    set(h.ax_show3D_unit,'cameraviewangle',10);
    view(-39,31)
    h.ax_show3D_prim = axes('parent',h.frame_show3D_prim);
    set(h.ax_show3D_prim,'cameraviewangle',10);
    view(-39,31)
    % AXES: wait bar
    h.ax_waitbar = axes(  'parent',   h.frame(2),...
                          'position', [.01 .01 .4 .03],...
                          'visible',  'off');
    
%     % TEXT: slider name of transparency
%     h.text_slider_show3D = uicontrol( 'parent',          h.frame(2),...
%                                       'style',           'text',...
%                                       'units',           'normalized',...
%                                       'string',          'transparency: ',...
%                                       'backgroundcolor', bcolor,...
%                                       'ForegroundColor', [0 0 0],...
%                                       'fontsize',        16,...
%                                       'HorizontalAlignment', 'right',...
%                                       'visible',         'off',...
%                                       'position',        [.1, .09, .19, .05]);
%     % SLIDER: slider of transparency
%     h.slider_show3D = uicontrol( 'parent',     h.frame(2),... 
%                                  'style',      'slider',...
%                                  'units',      'normalized',...
%                                  'position',   [.3 .1 .6 .03],...
%                                  'max',        1,...
%                                  'min',        0,...
%                                  'SliderStep', [0.05 0.05],...
%                                  'visible',    'off',...
%                                  'value',      .2);
    
    %% frame(3) contents - load, save, run, close
    %set push button position
    push_postion=[ .1   .1   .4  .4
                   .1   .55  .4  .4
                   .55  .1   .4  .4
                   .55  .55  .4  .4 ];  
    push_postion(:,1:2) = push_postion(:,1:2)-.02;     
    push_string         = {'Run' 'Load' 'Close' 'Save' '' '' ''};
    npush               = size(push_postion,1);
    for i = 1:npush
        h.push(i) = uicontrol( 'parent',          h.frame(3),...
                               'style',           'push',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'position',        push_postion(i,:),...
                               'string',          push_string{i},...
                               'fontsize',        24);
    end
    
    %% frame(4) contents
    %subpanel name
    gtext = {'Mode' 'Domain' 'Material' 'Lattice' 'Boundary condition','Eigen Solver'};
    %set subpanels
    for i = 1:length(gtext)
        h.subframe(i) = uipanel( 'parent',          h.frame(4),...
                                 'units',           'normalized',...
                                 'title',           gtext{i},...
                                 'backgroundcolor', bcolor,...
                                 'ForegroundColor', [.5 0 1],...
                                 'visible',         'off',...
                                 'fontsize',        18,...
                                 'position',        [.01 .01 .01 .01]);
    end
    set( h.subframe(1),'visible','on','position',[.05 .15 .9 .83]) %ï¿½ï¿½lï¿½ï¿½ï¿?Mode ï¿½ï¿½ panel
    %ï¿½]ï¿½wï¿½Uï¿½Ô¦ï¿½ï¿½ï¿½ï¿?ï¿½à´«ï¿½Wï¿½zï¿½Dï¿½Dï¿½ï¿½ panel ï¿½ï¿½)
    popup_option = [];
    for i = 1:length(gtext)
        popup_option = [popup_option gtext{i} '|'];
    end
    popup_option(end) = [];
    h.popup_menu = uicontrol( 'parent',          h.frame(4),...
                              'style',           'popup',...
                              'units',           'normalized',...
                              'ForegroundColor', [1 0 .5],...
                              'string',          popup_option,...
                              'fontsize',        16,...
                              'position',        [.05 .05 .9 .05]);
    %  sub-panel ï¿½]ï¿½w - Mode
    h.buttongroup(1) = uibuttongroup( 'parent',          h.subframe(1),...
                                      'backgroundcolor', bcolor,...
                                      'borderwidth',     0,...
                                      'visible',         'on',...
                                      'Position',        [0.1 0.35 .8 .5]);
%                                       'Position',        [0.1 0.7 .8 .25]);
    mode_name = {'Isotropic', 'Bi-isotropic', 'Anisotropic'};
    for i=1:length(mode_name)
        h.radio_mode(i) = uicontrol( 'parent',          h.buttongroup(1),...
                                     'style',           'radio',...
                                     'units',           'normalized',...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [1 0 .5],...
                                     'string',          mode_name{i},...
                                     'fontsize',        16,...
                                     'position',        [.05 1-i*.35 .9 .45],...
                                     'enable',          'on');
    end
    % sub-panel ï¿½]ï¿½w - Domain
    pp      = [.8 .48 .21 ;.2 .32 .27];
    gdomain = {'grid numbers' 'lattice constants' 'shape'}; % ï¿½Ð³yï¿½Tï¿½ï¿½sub-sub-panel
    for i = 1:length(gdomain)
        h.subsubframe(i) = uipanel( 'parent',          h.subframe(2),...
                                    'units',           'normalized',...
                                    'title',           gdomain{i},...
                                    'backgroundcolor', bcolor,...
                                    'ForegroundColor', [.5 0 1],...
                                    'fontsize',        14,...
                                    'position',        [.05 pp(1,i) .9 pp(2,i)]);
    end 
   
% ï¿½]ï¿½w x,y,z ï¿½Tï¿½Ó¤ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Æ¥Ø©Ò¥Îªï¿½frame 
    cc      = {'x:' 'y:' 'z:'};
    dstring = [16,16,16];
    for i = 1:3
        h.text_domain.grid_num(i) = uicontrol( 'parent',          h.subsubframe(1),...
                                        'style',           'text',...
                                        'units',           'normalized',...
                                        'string',          cc{i},...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.2 0 1],...
                                        'fontsize',        16,...
                                        'position',        [(i-1)*.3 .15 .1 .5]);
        h.edit_domain.grid_num(i) = uicontrol( 'parent',          h.subsubframe(1),...
                                        'style',           'edit',...
                                        'units',           'normalized',...
                                        'string',          int2str(dstring(i)),...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.5 0 1],...
                                        'fontsize',        14,...
                                        'position',        [(i-1)*.3+.1 .05 .2 .7]);
    end
% ï¿½]ï¿½wlattice constantï¿½Ò¥Îªï¿½frame  
    cc      = {'a:' 'b:' 'c:'};
    dstring = [1,1,1];
    for i = 1:3
        h.text_domain.lattice_constant(i) = uicontrol( 'parent',          h.subsubframe(2),...
                                    'style',           'text',...
                                    'units',           'normalized',...
                                    'string',          cc(i),...
                                    'backgroundcolor', bcolor,...
                                    'ForegroundColor', [.2 0 1],...
                                    'fontsize',        16,...
                                    'position',        [(i-1)*.34 .55 .12 .345]);
        h.edit_domain.lattice_constant(i) = uicontrol( 'parent',          h.subsubframe(2),...
                                    'style',           'edit',...
                                    'units',           'normalized',...
                                    'string',          num2str(dstring(i)),...
                                    'backgroundcolor', bcolor,...
                                    'ForegroundColor', [.5 0 1],...
                                    'fontsize',        14,...
                                    'position',        [(i-1)*.34+.12 .55 .19 .345],...
                                    'value',           i);
    end
    cc      = {'£\:' '£]:' '£^:'};
    dstring = [1/2,1/2,1/2];
    for i = 1:3
        h.text_domain.lattice_constant(3+i) = uicontrol( 'parent',          h.subsubframe(2),...
                                    'style',           'text',...
                                    'units',           'normalized',...
                                    'string',          cc(i),...
                                    'backgroundcolor', bcolor,...
                                    'ForegroundColor', [.2 0 1],...
                                    'fontsize',        16,...
                                    'position',        [(i-1)*.34 .05 .12 .345]);
        h.edit_domain.lattice_constant(3+i) = uicontrol( 'parent',          h.subsubframe(2),...
                                    'style',           'edit',...
                                    'units',           'normalized',...
                                    'string',          num2str(dstring(i)),...
                                    'backgroundcolor', bcolor,...
                                    'ForegroundColor', [.5 0 1],...
                                    'fontsize',        14,...
                                    'position',        [(i-1)*.34+.12 .05 .19 .345],...
                                    'value',           3+i );
    end
    

%     set(h.edit_domain(5:6),'enable','off');
    
%     shapetext         = {'Simple cubic','Semi woodpile', 'Face centered cubic', 'Body centered cubic'};%,'Semi woodpile(cylinder)','Woodpile','Scaffold','Scaffold rec'};                  
%     shape_option_name = {{'sphere radius:' 'cylinder radius:'} {'wood length:' 'wood width:' 'wood height:'} {'sphere radius:' 'cylinder radius:'} {'isolated number 1:' 'isolated number 2:'}};
    shape_option_name = {'sphere radius:' 'cylinder radius:'};
    dstring           = [0.12 0.1];
    
    h.sssframe = uipanel( 'parent',         h.subsubframe(3),...
                          'units',          'normalized',...
                          'backgroundcolor', bcolor,...
                          'ForegroundColor', [.5 0 1],...
                          'borderwidth',     0,...
                          'visible',         'on',...
                          'fontsize',        14,...
                          'position',        [.05 0.05 .9 .9]);
    for i = 1:length(shape_option_name)
        h.text_domain.shape(i) = uicontrol( 'parent',          h.sssframe,...
                                        'style',           'text',...
                                        'units',           'normalized',...
                                        'string',          shape_option_name{i},...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.2 0 1],...
                                        'fontsize',        14,...
                                        'position',        [.01 0.95-i*0.47  .41 .5],...
                                        'visible',         'on');                                
        h.edit_domain.shape(i) = uicontrol( 'parent',          h.sssframe,...
                                        'style',           'edit',...
                                        'units',           'normalized',...
                                        'string',          num2str(dstring(i)),...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.5 0 1],...
                                        'fontsize',        12,...
                                        'position',        [.43 0.95-i*.42  .56 .4],...
                                        'value',           i );
    end    
    cc = []; 
    if ismac || isunix
        para_file = dir([ pwd,'/PACKAGE/FAME_Material/FAME_Material_Locate_Parameter/No*.m']);
    else
        para_file = dir([ pwd,'\PACKAGE\FAME_Material\FAME_Material_Locate_Parameter\No*.m']);
    end
%     for i = 1:length(shapetext) % ï¿½]ï¿½wï¿½ï¿½ï¿?shape ï¿½Îªï¿½ï¿½Uï¿½Ô¦ï¿½ï¿½ï¿½ï¿?
%         cc = [cc shapetext{i} '|'];
%     end
    for i = 1:length(para_file) % ï¿½]ï¿½wï¿½ï¿½ï¿?shape ï¿½Îªï¿½ï¿½Uï¿½Ô¦ï¿½ï¿½ï¿½ï¿?
        data_name = para_file(i).name(1:end-2);
        cc = [cc data_name '|'];
    end
	cc(end) = [];
    h.popup_shape = uicontrol( 'parent',          h.subframe(2),...%h.frame(4),...
                               'style',           'popup',...
                               'units',           'normalized',...
                               'ForegroundColor', [1 0 .5],...
                               'string',          cc,...
                               'fontsize',        16,...
                               'position',        [.05 .05 .9 .05]);
    h.check_show3D = uicontrol( 'parent',h.subframe(2),...%h.frame(4),...  %ï¿½]ï¿½w show 3D structure ï¿½ï¶µ
                                     'style',           'check',...
                                     'units',           'normalized',...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [1 0 .5],...
                                     'string',          'Show 3D structure',... 
                                     'fontsize',        16,...
                                     'position',        [.05 .12 .9 .05]);
    
    % sub-panel ï¿½]ï¿½w - Material 
    set(h.subframe(3),'position',[0.001,.001,.0001,.0001]);
    cc      = {'permittivity:' 'permeability:' 'reciprocity:' 'chirality:' };
    dstring = [13 1 0 0];
    for i=1:4
        h.text_material(i) = uicontrol( 'parent',              h.subframe(3),...
                                        'style',               'text',...
                                        'units',               'normalized',...
                                        'string',              cc{i},...
                                        'backgroundcolor',     bcolor,...
                                        'ForegroundColor',     [.2 0 1],...
                                        'fontsize',            16,...
                                        'HorizontalAlignment', 'left',...
                                        'position',            [.05 1-(i)*.2  .35 .08]);
        h.edit_material(i) = uicontrol( 'parent',          h.subframe(3),...
                                        'style',           'edit',...
                                        'units',           'normalized',...
                                        'string',          int2str(dstring(i)),...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.5 0 1],...
                                        'fontsize',        14,...
                                        'position',        [.4 1-(i)*.2  .6 .08]);
    end
    set(h.edit_material(2),'enable','off');
    set(h.text_material(3:4),'visible','off')% ï¿½wï¿½]ï¿½ï¿½ isotropic, ï¿½Ò¥Hï¿½ï¿½ï¿½ï¿½Ü«ï¿½ï¿½ï¿?
    set(h.edit_material(3:4),'visible','off')
    % sub-panel ï¿½]ï¿½w - Lattice 
    pos = get(h.subframe(4),'position');
    set(h.subframe(4),'position',[0.001,.001,.0001,.0001]);
    SCtext = [ 'G: [ 0   , 0   , 0   ]'              
               'X: [ 0   , 0.5 , 0   ]'  
               'M: [ 0.5 , 0.5 , 0   ]'
               'R: [ 0.5 , 0.5 , 0.5 ]' ];
    FCCtext = ['X: [ 0    , 1    , 0    ]'              
               'U: [ 0.25 , 1    , 0.25 ]'  
               'L: [ 0.5  , 0.5  , 0.5  ]'
               'G: [ 0    , 0    , 0    ]'
               'W: [ 0.5  , 1    , 0    ]'
               'K: [ 0.75 , 0.75 , 0    ]'];
    BCCtext = [ 'L: [  0   , 0   , 0   ]'             
                'H: [  0   , 1   , 0   ]'
                'P: [ -1/2 , 1/2 , 1/2 ]'
                'N: [ -1/2 , 0   , 1/2 ]'
                'Z: [  0   , 0   , 1   ]'
                'Q: [ -1/2 , 1/4 , 1/2 ]'
                'J: [  0   , 3/4 , 0   ]'];
    for i=1:4 % ï¿½ï¿½ï¿?SC ï¿½P SW ï¿½Ò¹ï¿½ï¿½ï¿½ï¿½ï¿½ path points
        h.text_lattice_SC1(i) = uicontrol( 'parent',          h.subframe(4),...
                                          'style',           'text',...
                                          'units',           'normalized',...
                                          'string',          SCtext(i,1:3),...
                                          'backgroundcolor', bcolor,...
                                          'ForegroundColor', [.2 0 1],...
                                          'fontsize',        16,...
                                          'position',        [.05 1-i*.1  .1 .08],...
                                          'HorizontalAlignment', 'left',...
                                          'visible',         'on');
        h.text_lattice_SC2(i) = uicontrol( 'parent',          h.subframe(4),...
                                          'style',           'text',...
                                          'units',           'normalized',...
                                          'string',          SCtext(i,4:end),...
                                          'backgroundcolor', bcolor,...
                                          'ForegroundColor', [.2 0 1],...
                                          'fontsize',        16,...
                                          'position',        [.2 1-i*.1  .5 .08],...
                                          'visible',         'on');
    end
    for i=1:6 % ï¿½ï¿½ï¿?FCC ï¿½Ò¹ï¿½ï¿½ï¿½ï¿½ï¿½ path points
        h.text_lattice_FCC1(i) = uicontrol( 'parent',          h.subframe(4),...
                                           'style',           'text',...
                                           'units',           'normalized',...
                                           'string',          FCCtext(i,1:3),...
                                           'backgroundcolor', bcolor,...
                                           'ForegroundColor', [.2 0 1],...
                                           'fontsize',        16,...
                                           'position',        [.05 1-i*.1  .1 .08],...
                                           'HorizontalAlignment', 'left',...
                                           'visible',         'off');
        h.text_lattice_FCC2(i) = uicontrol( 'parent',          h.subframe(4),...
                                           'style',           'text',...
                                           'units',           'normalized',...
                                           'string',          FCCtext(i,4:end),...
                                           'backgroundcolor', bcolor,...
                                           'ForegroundColor', [.2 0 1],...
                                           'fontsize',        16,...
                                           'position',        [.2 1-i*.1  .5 .08],...
                                           'visible',         'off');
    end
    for i=1:7 % ï¿½ï¿½ï¿?BCC ï¿½Ò¹ï¿½ï¿½ï¿½ï¿½ï¿½ path points
        h.text_lattice_BCC1(i) = uicontrol( 'parent',          h.subframe(4),...
                                           'style',           'text',...
                                           'units',           'normalized',...
                                           'string',          BCCtext(i,1:3),...
                                           'backgroundcolor', bcolor,...
                                           'ForegroundColor', [.2 0 1],...
                                           'fontsize',        16,...
                                           'position',        [.05 1-i*.1  .1 .08],...
                                           'HorizontalAlignment', 'left',...
                                           'visible',         'off');
        h.text_lattice_BCC2(i) = uicontrol( 'parent',          h.subframe(4),...
                                           'style',           'text',...
                                           'units',           'normalized',...
                                           'string',          BCCtext(i,4:end),...
                                           'backgroundcolor', bcolor,...
                                           'ForegroundColor', [.2 0 1],...
                                           'fontsize',        16,...
                                           'position',        [.2 1-i*.1  .5 .08],...
                                           'visible',         'off');
    end
 
    h.text_lattice_show = uicontrol( 'parent',              h.subframe(4),...  % ï¿½ï¿½Ü¿ï¿½Ü¸ï¿½ï¿½|ï¿½ï¿½ text
                                     'style',               'text',...
                                     'units',               'normalized',...
                                     'string',              'Path: ',...
                                     'backgroundcolor',     bcolor,...
                                     'ForegroundColor',     [.2 0 1],...
                                     'fontsize',            16,...
                                     'HorizontalAlignment', 'left',...
                                     'position',            [.05 .15  .3 .08]);  
    h.edit_lattice_show = uicontrol( 'parent',          h.subframe(4),...
                                        'style',           'edit',...
                                        'units',           'normalized',...
                                        'string',          'GXMRG',...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.5 0 1],...
                                        'fontsize',        16,...
                                        'position',        [.2 .15  .75 .08]);
    h.text_lattice_part_num = uicontrol( 'parent',              h.subframe(4),...  % ï¿½ï¿½Ü¿ï¿½ï¿½partition numberï¿½ï¿½ text
                                     'style',               'text',...
                                     'units',               'normalized',...
                                     'string',              'Partition number: ',...
                                     'backgroundcolor',     bcolor,...
                                     'ForegroundColor',     [.2 0 1],...
                                     'fontsize',            16,...
                                     'HorizontalAlignment', 'left',...
                                     'position',            [.05 .05  .6 .08]);       
    h.edit_lattice_part_num = uicontrol( 'parent',          h.subframe(4),...
                                        'style',           'edit',...
                                        'units',           'normalized',...
                                        'string',          '4',...
                                        'backgroundcolor', bcolor,...
                                        'ForegroundColor', [.5 0 1],...
                                        'fontsize',        16,...
                                        'position',        [.5 .05  .45 .08]);
    % sub-panel ï¿½]ï¿½w - Boundary condition
    cc = {'x-axis: ' 'y-axis: ' 'z-axis: '};
    cc_bc = {'quasi-periodic condition'};
    for i = 1:3
        h.text_boundary{i} = uicontrol( 'parent',              h.subframe(5),... 
                                        'style',               'text',...
                                        'units',               'normalized',...
                                        'string',              cc{i},...
                                        'backgroundcolor',     bcolor,...
                                        'ForegroundColor',     [.2 0 1],...
                                        'fontsize',            16,...
                                        'HorizontalAlignment', 'left',...
                                        'position',            [.05 .89-(i-1)*.15  .24 .08]);  
        h.popup_boundary{i} = uicontrol( 'parent',          h.subframe(5),...
                                         'style',           'popup',...
                                         'units',           'normalized',...
                                         'ForegroundColor', [1 0 .5],...
                                         'string',          cc_bc,...
                                         'fontsize',        16,...
                                         'position',        [.3 .9-(i-1)*.15 .68  .08]);    
    end
    % sub-panel ï¿½]ï¿½w - Eigen Solver
    h.buttongroup(2) = uibuttongroup( 'parent',          h.subframe(6),...
                                      'backgroundcolor', bcolor,...
                                      'borderwidth',     0,...
                                      'visible',         'on',...
                                      'Position',        [0.1 0.7 .8 .25]);
    cc = {'EIGS (matlab)' 'JD-SIRA'};
    for i = 1:length(cc)
        h.radio_eigensolver(i) =uicontrol( 'parent',          h.buttongroup(2),...%h.frame(4),...
                                           'style',           'radio',...
                                           'units',           'normalized',...
                                           'ForegroundColor', [1 0 .5],...
                                           'backgroundColor', bcolor,...
                                           'string',          cc{i},...
                                           ...%'callback',{@cb2,hsubframe},...
                                           'fontsize',        16,...
                                           'position',        [.05 1-i*.4-.1 .9 .4]);
    end
    
    
    
    