function FAME_GUI_User_Defined()

FAME_Folder_Manager( )

% if ismac || isunix
%     addpath PACKAGE/FAME_GUI/
%     addpath PACKAGE/FAME_GUI/GUI_Call_Back_functions_user_defined
%     addpath PACKAGE/FAME_GUI/GUI_eigenmode 
%     addpath PACKAGE/FAME_GUI/GUI_Plot_material
%     addpath PACKAGE/FAME_GUI/GUI_User_Defined
% else 
    addpath PACKAGE\FAME_GUI\
    addpath PACKAGE\FAME_GUI\GUI_Call_Back_functions_user_defined
    addpath PACKAGE\FAME_GUI\GUI_eigenmode 
    addpath PACKAGE\FAME_GUI\GUI_Plot_material
    addpath PACKAGE\FAME_GUI\GUI_User_Defined
% end

%% Setting main frame %視窗界面
bcolor = [1 1 1 ]/1.1;%/255;%[1 0 1];
h.fig  = figure(1);clf

set(h.fig, 'position',    [0 0 1080 720],... %視窗左下，右上的相對坐標
           'color',       bcolor,...
           'menubar',     'none',...
           'toolbar',     'none',... %關閉工具列
           'name',        'FAME-User Defined',...
           'numbertitle', 'off');
%% Setting main panels %設定視窗分割成哪些部分（左右）
%panels position
frame_postion = [    0       0  0.5  1      
                     0.5     0  0.5  1 ];  %分成幾個子視窗，及相對比例
nframe      = size(frame_postion,1);
%set panel
for i = 1:nframe
    h.frame(i) = uipanel( 'parent',          h.fig,...
                          'units',           'normalized',... %計算物件範圍大小都以比例算
                          'backgroundcolor', bcolor,...
                          'ForegroundColor', [1 1 1],...
                          'shadowcolor',     [.9 .9 .98]/3,...
                          'bordertype',      'beveledin',...
                          'borderwidth',     4,...
                          'position',        frame_postion(i,:));
end
%% frame(1) contents
Script_frame
%% frame(2) contents %右邊分成三個部分
subpanel_position      = [ 0.01 0.01 0.985 0.88/3;
                           0.01 0.88/3+2*0.03-0.02 0.985 0.88/3;
                           0.01 2*0.88/3+3*0.03-0.02 0.985 0.88/3+0.05];
subpanel_title = {'Domain', 'Object','Action'};
h.frame_Domain = uipanel( 'parent',          h.frame(2),...
                          'units',           'normalized',...
                          'backgroundcolor', [.9 .9 .9],...
                          'ForegroundColor', [0 0 0],...
                          'shadowcolor',     [0 0 0],...
                          'title',           subpanel_title{1},...
                          'position',        subpanel_position(3,:),... 
                          'fontsize',        17,...
                          'visible',         'on');
h.frame_Object = uipanel( 'parent',          h.frame(2),...
                          'units',           'normalized',...
                          'backgroundcolor', bcolor,...
                          'ForegroundColor', [0 0 0],...
                          'shadowcolor',     [0 0 0],...
                          'title',           subpanel_title{2},...
                          'position',        subpanel_position(2,:),...
                          'fontsize',        17,...
                          'visible',         'on');
h.frame_Action = uipanel( 'parent',          h.frame(2),...
                          'units',           'normalized',...
                          'backgroundcolor', bcolor,...
                          'ForegroundColor', [0 0 0],...
                          'shadowcolor',     [0 0 0],...
                          'title',           subpanel_title{3},...
                          'position',        subpanel_position(1,:),... 
                          'fontsize',        17,...
                          'visible',         'on');                      
%% Domain penal
h.text_type = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'text',... %物件屬性－文字
                         'units',           'normalized',...
                         'string',          'Lattice type :',... %文字名稱
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        14,...
                         'position',        [0 .83 .3 0.15]);
type_name = {'Simple Cubic','Face Centered Cubic', 'Body Centered Cubic',...
             'Hexagonal','Rhombohedral','Simple Tetragonal','Body Centered Tetragonal', 'Simple Orthorhombic', 'Face Centered Orthorhombic', 'Body Centered Orthorhombic',...
             'A-Base Centered Orthorhombic', 'C-Base Centered Orthorhombic','Simple Monoclinic','Base Centered Monoclinic','Triclinic'};
h.pop_type = uicontrol( 'parent',          h.frame_Domain,...
                        'style',           'popup',... %屬性：下拉式選單
                        'units',           'normalized',...
                        'ForegroundColor', [0 0 0],...
                        'string',          type_name,...
                        'fontsize',        12,...
                        'position',        [0.27 .83 .4 0.16]);
h.text_grid = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'text',...
                         'units',           'normalized',...
                         'string',          'Grid numbers :',...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        14,...
                         'position',        [0 .65 .3 0.15]);
h.edit_grid = uicontrol( 'parent',          h.frame_Domain,...
                        'style',           'edit',...   %屬性：填空表單
                        'units',           'normalized',...
                        'ForegroundColor', [0 0 0],...
                        'string',          '[16 16 16]',...
                        'fontsize',        12,...
                        'position',        [.27 .70 .2 0.12]  );
h.frame_constant = uipanel( 'parent',          h.frame_Domain,...
                                   'units',           'normalized',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'shadowcolor',     [0 0 0],...
                                   'title',           'Lattice Constants',...
                                   'fontsize',        12,...
                                   'position',        [0.01 0.01 0.58 0.7],... 
                                   'visible',         'on');     
h.text_Lattice_Constant_material = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'push',...
                         'units',           'normalized',...
                         'string',          'Add parameter',...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.5 .7 .27 0.12],...
                         'visible',         'off');
h.list_text = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'push',...
                         'units',           'normalized',...
                         'string',          'Add parameter',...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.5 .7 .27 0.12]);

h.frame_lattice_parameter = uipanel( 'parent',          h.frame_Domain,...
                                          'units',           'normalized',...
                                          'backgroundcolor', bcolor,...
                                          'ForegroundColor', [0 0 0],...
                                          'shadowcolor',     [0 0 0],...
                                          'title',           'Material Parameter',...
                                          'position',        [0.6 .01 .4 .67],... 
                                          'fontsize',        12,...
                                          'visible',         'on');                  
h.list_parameter_material = uicontrol( 'parent',          h.frame_lattice_parameter,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [.01 .01 .98 .98],...
                         'visible',         'off');
h.list_parameter = uicontrol( 'parent',           h.frame_lattice_parameter,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [.01 .01 .98 .98]);
h.clear          = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'push',...
                         'units',           'normalized',...
                         'string',          'CLEAR',...
                         'fontname',        'Time New Roman',...
                         'backgroundcolor', 'y',...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.8 .7 .19 0.12]);
h.save          = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'push',...
                         'units',           'normalized',...
                         'string',          'Save',...
                         'fontname',        'Time New Roman',...
                         'backgroundcolor', 'y',...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        14,...
                         'position',        [0.83 .84 .12 0.13]);  
h.load          = uicontrol( 'parent',          h.frame_Domain,...
                         'style',           'push',...
                         'units',           'normalized',...
                         'string',          'Load',...
                         'fontname',        'Time New Roman',...
                         'backgroundcolor', 'y',...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        14,...
                         'position',        [0.7 .84 .12 0.13]);  
% set(h.frame_constant{1},'visible','on')
%%%%%%%%%%%%%%%%%%%%%%%%
%Script_Lattice_Constant%
Script_Lattice_Constant_control
Script_Lattice_parameter%
%%  Object penal
% 大物件
Script_object_panel
% 暫存元素資訊
Script_element_tempinfo
% 元素資訊介面-文字與編輯
Script_element_info
Script_element_edit
% 材料參數資訊
Script_material_parameter
Script_shape_parameter                                                              
%% Action penal
h.push_delete = uicontrol( 'parent',          h.frame_Action,...
                           'style',           'push',...
                           'units',           'normalized',...
                           'ForegroundColor', [0 0 0],...
                           'position',        [0.02 0.7 0.23 0.22],...
                           'string',          'Object Delete',...
                           'fontsize',        12);
% h.push_property = uicontrol( 'parent',          h.frame_Action,...
%                            'style',           'push',...
%                            'units',           'normalized',...
%                            'ForegroundColor', [0 0 0],...
%                            'position',        [0.02 0.4 0.23 0.22],...
%                            'string',          'Object Property',...
%                            'fontsize',        12);
% h.push_export = uicontrol( 'parent',          h.frame_Action,...
%                            'style',           'push',...
%                            'units',           'normalized',...
%                            'ForegroundColor', [0 0 0],...
%                            'position',        [0.02 0.1 0.23 0.22],...
%                            'string',          'Export Matrices',...
%                            'fontsize',        12);
                       
h.list_current_material_sphere = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .8]);
h.list_current_material_cylinder  = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.65 .05 .3 .8]);                        
Script_object_tempinfo
%% Setting Call Back
% 改變lattice type後，lattice constant表格變化
set(  h.pop_type     , 'callback', {@Call_Back_pop_type,h}      );
% 更動lattice constant.
set(h.edit_constant_a,'callback',{@Call_Back_rewrite_Lattice_constant,h});
set(h.edit_constant_b,'callback',{@Call_Back_rewrite_Lattice_constant,h});
set(h.edit_constant_c,'callback',{@Call_Back_rewrite_Lattice_constant,h});
set(h.edit_constant_alpha,'callback',{@Call_Back_rewrite_Lattice_constant,h});
set(h.edit_constant_beta,'callback',{@Call_Back_rewrite_Lattice_constant,h});
set(h.edit_constant_gamma,'callback',{@Call_Back_rewrite_Lattice_constant,h});

set(  h.push_sphere  , 'callback', {@Call_Back_push_sphere,h}   );
%
set(  h.push_cylinder, 'callback', {@Call_Back_push_cylinder,h} );
%
%set(  h.push_handle  , 'callback', {@Call_Back_push_handle,h}   );
% 儲存參數
set(  h.list_text    , 'callback', {@Call_Back_list_text,h}     );
%
set(  h.push_element , 'callback', {@Call_Back_push_element,h}  );
set(  h.clear        , 'callback', {@Call_Back_clear,h}   );
%information
set(  h.element_parameter    , 'callback', {@Call_Back_element_edit,h}     );
% edit element information in GUI panel
Script_element_handle
% delete
set(  h.push_delete          , 'callback', {@Call_Back_object_delete,h}    );
%% creat and load the script 
set(  h.save                 , 'callback', {@Call_Back_save,h} );
set(  h.load                 , 'callback', {@Call_Back_load,h} );
end