% This script set text and edit for shape parameters

%% 1. Sphere parameters
h.text_sphere_center = uicontrol( 'parent',          h.frame_shape_parameter_sphere,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Sphere center :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .7 .6 0.2]);
h.edit_sphere_center = uicontrol( 'parent',          h.frame_shape_parameter_sphere,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .7 .35 0.2],...
                                 'enable',          'off');
h.text_sphere_radius = uicontrol( 'parent',          h.frame_shape_parameter_sphere,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Sphere radius :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .5 .6 0.2]);
h.edit_sphere_radius = uicontrol( 'parent',          h.frame_shape_parameter_sphere,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .5 .35 0.2],...
                                 'enable',          'off');           
%% 2. Cylinder parameters
h.text_cylinder_bot_center = uicontrol( 'parent',    h.frame_shape_parameter_cylinder,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Cylinder bot center :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .7 .6 0.2]);
h.edit_cylinder_bot_center = uicontrol( 'parent',   h.frame_shape_parameter_cylinder,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .7 .35 0.2],...
                                 'enable',          'off');
h.text_cylinder_top_center = uicontrol( 'parent',    h.frame_shape_parameter_cylinder,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Cylinder top center :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .4 .6 0.2]);
h.edit_cylinder_top_center = uicontrol( 'parent',   h.frame_shape_parameter_cylinder,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .4 .35 0.2],...
                                 'enable',          'off');                             
h.text_cylinder_radius = uicontrol( 'parent',        h.frame_shape_parameter_cylinder,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Cylinder radius :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .1 .6 0.2]);
h.edit_cylinder_radius = uicontrol( 'parent',       h.frame_shape_parameter_cylinder,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .1 .35 0.2],...
                                 'enable',          'off');           
%% 3. Handle parameters                   
h.text_sphere_radius_handle = uicontrol( 'parent',          h.frame_shape_parameter_handle,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Sphere radius :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .7 .6 0.2]);
h.edit_sphere_radius_handle = uicontrol( 'parent',          h.frame_shape_parameter_handle,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .7 .35 0.2],...
                                 'enable',          'off');
h.text_cylinder_radius_handle = uicontrol( 'parent',        h.frame_shape_parameter_handle,...
                                  'style',           'text',...
                                  'units',           'normalized',...
                                  'string',          'Cylinder radius :',...
                                  'backgroundcolor', bcolor,...
                                  'ForegroundColor', [0 0 0],...
                                  'fontsize',        12,...
                                  'position',        [.02 .4 .6 0.2]);
h.edit_cylinder_radius_handle = uicontrol( 'parent',       h.frame_shape_parameter_handle,...
                                 'style',           'edit',...
                                 'units',           'normalized',...
                                 'ForegroundColor', [0 0 0],...
                                 'string',          '',...
                                 'fontsize',        12,...
                                 'position',        [.63 .4 .35 0.2],...
                                 'enable',          'off');                                   