h.object_tempinfo_sphere = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_sphere_center = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_sphere_material = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_sphere_radius = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_cylinder_material = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_cylinder_top = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_cylinder_bot = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');
h.object_tempinfo_cylinder_radius = uicontrol( 'parent',          h.frame_Action,...
                                     'style',           'listbox',...
                                     'units',           'normalized',...
                                     'string',          {},...
                                     'backgroundcolor', bcolor,...
                                     'ForegroundColor', [0 0 0],...
                                     'fontsize',        12,...
                                     'position',        [.32 .05 .3 .4],...
                                     'visible',         'off');