h.element_color = uicontrol( 'parent',    h.frame_Object,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.6 .01 .18 .67],...
                         'visible',         'off');
h.element_permitt = uicontrol( 'parent',    h.frame_Object,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.8 .01 .18 .67],...
                         'visible',         'off');
h.element_permeab = uicontrol( 'parent',    h.frame_Object,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.8 .01 .18 .67],...
                         'visible',         'off');
h.element_xi = uicontrol( 'parent',    h.frame_Object,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.8 .01 .18 .67],...
                         'visible',         'off');
h.element_zeta = uicontrol( 'parent',    h.frame_Object,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.8 .01 .18 .67],...
                         'visible',         'off');
                     