% 輸入參數用
%% 1. parameters
% h.text_parameter = uicontrol( 'parent',          h.frame_lattice_parameter,...
%                                   'style',           'text',...
%                                   'units',           'normalized',...
%                                   'string',          'Parameter name :',...
%                                   'backgroundcolor', bcolor,...
%                                   'ForegroundColor', [0 0 0],...
%                                   'fontsize',        12,...
%                                   'position',        [.02 .7 .6 0.2],...
%                                   'visible',          'off');
% h.edit_parameter = uicontrol( 'parent',          h.frame_lattice_parameter,...
%                                  'style',           'edit',...
%                                  'units',           'normalized',...
%                                  'ForegroundColor', [0 0 0],...
%                                  'string',          'Value',...
%                                  'fontsize',        12,...
%                                  'position',        [.63 .7 .35 0.2],...
%                                  'enable',          'off');
