%Primitive cell
h.frame_display_shape_primitive = uipanel( 'parent',          h.frame(1),...
                                'units',           'normalized',...
                                'title',           'Primitive',...
                                'backgroundcolor', bcolor,...
                                'ForegroundColor', [0 0 0],...
                                'shadowcolor',     [.9 .9 .98]/3,...
                                'bordertype',      'beveledin',...
                                 'borderwidth',     4,...
                                'position',        [0,0.5,1,0.5],... 
                                'visible',         'on');
%Unit cell
h.frame_display_shape_unit = uipanel( 'parent',          h.frame(1),...
                                 'units',           'normalized',...
                                 'title',           'Unit',...
                                 'backgroundcolor', [1 1 1],...
                                 'ForegroundColor', [0 0 0],...
                                 'shadowcolor',     [.9 .9 .98]/3,...
                                 'bordertype',      'beveledin',...
                                 'borderwidth',     4,...
                                 'position',        [0,0,1,0.5],...  
                                 'visible',         'on');

%B matrix
% h.frame_display_grid = uipanel( 'parent',          h.frame(1),...
%                                 'units',           'normalized',...
%                                 'title',           'Grids',...
%                                 'backgroundcolor', bcolor,...
%                                 'ForegroundColor', [0 0 0],...
%                                 'shadowcolor',     [.9 .9 .98]/3,...
%                                 'bordertype',      'beveledin',...
%                                 'borderwidth',     4,...
%                                 'position',        [0,0.7,1,0.3],... 
%                                 'visible',         'on');                             
h.ax_display_shape_primitive = axes( 'parent',   h.frame_display_shape_primitive,...
                          'position', [.05 .1 .9 .9],...
                          'color',    [1 1 1],...
                          'xTick',    [],...
                          'yTick',    [],...
                          'box',      'on',...
                          'visible',  'on');
h.ax_display_shape_unit = axes( 'parent',   h.frame_display_shape_unit,...
                          'position', [.05 .1 .9 .9],...
                          'color',    [1 1 1],...
                          'xTick',    [],...
                          'yTick',    [],...
                          'box',      'on',...
                          'visible',  'on');
%plot_mode = 'primitive_cell';                      
%FAME_Plot_Material_User_Defined([1 0 0],[0 1 0],[0 0 1],[], h.ax_display_shape,plot_mode);           

% h.push_export_shape = uicontrol( 'parent',    h.frame_display_shape_unit,...
%                            'style',           'push',...
%                            'units',           'normalized',...
%                            'ForegroundColor', [0 0 0],...
%                            'position',        [0.2 0.01 0.6 0.13],...
%                            'string',          'Open figure in new windows',...
%                            'fontsize',        12);
% h.ax_display_grid = axes( 'parent',   h.frame_display_grid,...
%                           'position', [.05 .15 .9 .9],...
%                           'color',    [1 1 1],...
%                           'xTick',    [],...
%                           'yTick',    [],...
%                           'box',      'on',...
%                           'visible',  'on');
% h.push_construct_grid = uicontrol( 'parent',    h.frame_display_grid,...
%                                    'style',           'push',...
%                                    'units',           'normalized',...
%                                    'ForegroundColor', [0 0 0],...
%                                    'position',        [0.2 0.01 0.6 0.13],...
%                                    'string',          'Construct Material Matrices',...
%                                    'fontsize',        12);                        
% set(h.ax_display_grid,'xTick',[]);                     
% axis off;