h.frame_shape_parameter_sphere = uipanel( 'parent',          h.frame_Object,...
                                          'units',           'normalized',...
                                          'backgroundcolor', bcolor,...
                                          'ForegroundColor', [0 0 0],...
                                          'shadowcolor',     [0 0 0],...
                                          'title',           'Shape Parameters',...
                                          'position',        [0.4 0.05 0.59 0.81],... 
                                          'visible',         'off');
h.frame_shape_parameter_cylinder = uipanel( 'parent',          h.frame_Object,...
                                          'units',           'normalized',...
                                          'backgroundcolor', bcolor,...
                                          'ForegroundColor', [0 0 0],...
                                          'shadowcolor',     [0 0 0],...
                                          'title',           'Shape Parameters',...
                                          'position',        [0.4 0.05 0.59 0.81],... 
                                          'visible',         'off');
h.frame_shape_parameter_handle = uipanel( 'parent',          h.frame_Object,...
                                          'units',           'normalized',...
                                          'backgroundcolor', bcolor,...
                                          'ForegroundColor', [0 0 0],...
                                          'shadowcolor',     [0 0 0],...
                                          'title',           'Shape Parameters',...
                                          'position',        [0.4 0.05 0.59 0.81],... 
                                          'visible',         'off');    