%%
h.push_sphere = uicontrol( 'parent',          h.frame_Object,...
                           'style',           'push',...
                           'units',           'normalized',...
                           'ForegroundColor', [0 0 0],...
                           'position',        [0.02 0.49 0.25 0.22],...
                           'string',          'Add Sphere',...
                           'fontsize',        12);
h.push_cylinder = uicontrol( 'parent',          h.frame_Object,...
                             'style',           'push',...
                             'units',           'normalized',...
                             'ForegroundColor', [0 0 0],...
                             'position',        [0.02 0.25 0.25 0.22],...
                             'string',          'Add Cylinder',...
                             'fontsize',        12);
%h.push_handle = uicontrol( 'parent',          h.frame_Object,...
%                              'style',           'push',...
%                              'units',           'normalized',...
%                              'ForegroundColor', [0 0 0],...
%                              'position',        [0.02 .01 .25 0.22],...
%                              'string',          'Add Handle',...
%                              'fontsize',        12);
h.push_element = uicontrol( 'parent',          h.frame_Object,...
                         'style',           'push',...
                         'units',           'normalized',...
                         'string',          'Add Element',...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [0.02 0.73 0.25 0.22]);
                     
%%
 h.element_table = uipanel( 'parent',          h.frame_Object,...
                                   'units',           'normalized',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'shadowcolor',     [0 0 0],...
                                   'title',           'Element',...
                                   'fontsize',        13,...
                                   'position',        [0.29 .01 .13 .98],... 
                                   'visible',         'on');
%%
h.element_parameter = uicontrol( 'parent',    h.element_table,...
                         'style',           'listbox',...
                         'units',           'normalized',...
                         'string',          {},...
                         'backgroundcolor', bcolor,...
                         'ForegroundColor', [0 0 0],...
                         'fontsize',        12,...
                         'position',        [.01 .01 .99 .99]);
 h.element_info{1} = uipanel( 'parent',          h.frame_Object,...
                                   'units',           'normalized',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'shadowcolor',     [0 0 0],...
                                   'title',           'Information of the element',...
                                   'fontsize',        13,...
                                   'position',        [0.43 .01 .56 .98],... 
                                   'visible',         'on');