h.element_edit{1} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'edit',...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           '',...
                                   'fontsize',        12,...
                                   'position',        [.21 .88 .13 .12]);              
h.element_edit{2} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'edit',...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           '',...
                                   'fontsize',        12,...
                                   'position',        [0.67 .88 .32 .12]);     
h.element_edit{3} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'edit',...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           '',...
                                   'fontsize',        12,...
                                   'position',        [.35 .72 .12 .13]);   
h.element_edit{4} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'edit',...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           '',...
                                   'fontsize',        12,...
                                   'position',        [.86 .72 .12 .13]);  
h.element_edit{5} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'edit',...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           '',...
                                   'fontsize',        12,...
                                   'position',        [0.82 .42 .12 .13]);  
h.element_edit{6} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'edit',...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           '',...
                                   'fontsize',        12,...
                                   'position',        [0.82 0.27 .12 .13]);  