h.element_info{2} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'text',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           'Name :',...
                                   'fontsize',        12,...
                                   'position',        [.01 .8 .21 .2]);               
h.element_info{3} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'text',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           'Color (RGB) :',...
                                   'fontsize',        12,...
                                   'position',        [.26 .8 .5 .2]);     
h.element_info{4} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'text',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           'Permittivity :',...
                                   'fontsize',        12,...
                                   'position',        [0.01 .45 .35 .4]);   
h.element_info{5} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'text',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           'Permeability :',...
                                   'fontsize',        12,...
                                   'position',        [.42 .45 .5 .4]);  
h.element_info{6} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'text',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           'Electromagnetic parameter £i :',...
                                   'fontsize',        12,...
                                   'position',        [0 .15 .88 .4]);  
h.element_info{7} = uicontrol( 'parent',          h.element_info{1},...
                                   'units',           'normalized',...
                                   'style',           'text',...
                                   'backgroundcolor', bcolor,...
                                   'ForegroundColor', [0 0 0],...
                                   'string',           'Electromagnetic parameter £a :',...
                                   'fontsize',        12,...
                                   'position',        [0 0 .88 .4]);  