% This script set text and edit for lattice constants


%% 1. Simple Cubic lattice
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{1},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{1},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
%% 2. Face Centered Cubic lattice
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{2},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{2},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
%% 3. Body Centered Cubic lattice
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{3},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{3},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  ); 
%% 4. Hexagonal lattice


h.text_constant_a = uicontrol( 'parent',          h.frame_constant{4},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{4},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{4},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{4},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
%% 5. Rhombohedral lattice

h.text_constant_a = uicontrol( 'parent',          h.frame_constant{5},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{5},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{5},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{5},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
%% 6. Simple Tetragonal
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{6},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{6},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{6},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{6},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
%% 7. Body Centered Tetragonal
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{7},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{7},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{7},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{7},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
%% 8. Simple Orthorhombic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{8},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{8},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{8},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{8},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{8},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{8},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
%% 9. Face Centered Orthorhombic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{9},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{9},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{9},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{9},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{9},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{9},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
%% 10. Body Centered Orthorhombic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{10},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{10},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{10},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{10},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{10},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{10},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
%% 11.  A-Base Centered Orthorhombic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{11},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{11},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{11},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{11},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{11},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{11},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
%% 12. C-Base Centered Orthorhombic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{12},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{12},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{12},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{12},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{12},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{12},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
%% 13. Simple Monoclinic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
h.text_constant_gamma = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          '£^ = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.36 .2 0.14]);
h.edit_constant_gamma = uicontrol( 'parent',          h.frame_constant{13},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .36 .6 0.14]  ); 
%% 14. Base Centered Monoclinic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  );
h.text_constant_gamma = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          '£^ = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.36 .2 0.14]);
h.edit_constant_gamma = uicontrol( 'parent',          h.frame_constant{14},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .36 .6 0.14]  ); 
%% 15. Triclinic
h.text_constant_a = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'a = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .84 .2 0.14]);
h.edit_constant_a = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .84 .6 0.14]  );
h.text_constant_b = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'b = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.68 .2 0.14]);
h.edit_constant_b = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .68 .6 0.14]  ); 
h.text_constant_c = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          'c = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.52 .2 0.14]);
h.edit_constant_c = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .52 .6 0.14]  ); 
h.text_constant_alpha = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          '£\ = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 .36 .2 0.14]);
h.edit_constant_alpha = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .36 .6 0.14]  );
h.text_constant_beta = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          '£] = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.20 .2 0.14]);
h.edit_constant_beta = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .20 .6 0.14]  ); 
h.text_constant_gamma = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'text',...
                               'units',           'normalized',...
                               'string',          '£^ = ',...
                               'backgroundcolor', bcolor,...
                               'ForegroundColor', [0 0 0],...
                               'fontsize',        12,...
                               'position',        [.1 0.04 .2 0.14]);
h.edit_constant_gamma = uicontrol( 'parent',          h.frame_constant{15},...
                               'style',           'edit',...
                               'units',           'normalized',...
                               'ForegroundColor', [0 0 0],...
                               'string',          '1',...
                               'fontsize',        12,...
                               'position',        [.35 .04 .6 0.14]  ); 

                           
